### ISSUE TITLE
USER STORY: Install Django with Cloudinary

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kkimages-api#1]
As a **Developer** I can **set up Django and install the initial supporting libraries** so that **I am ready to start development**

## Acceptance Criteria 1
**Given** that this is a new project
**When** we want users to share information through the app
**Then** Django Rest framework can be used for this project

## Tasks
- [x] Task 1 – Install Django, gunicorn and Pillow
- [x] Task 2 – Install django-cloudinary-storage
- [x] Task 3 – Create and setup env.py
- [x] Task 4 – Update settings.py

## EPIC
1. #5
