### ISSUE TITLE
USER STORY: Create app for photos

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kkimages-api#10]
As a **Developer** I can **add new apps to my project** so that **the project can be easily managed**

## Acceptance Criteria 1
**Given** that we have a database design
**When** we have a project to build apps on
**Then** we can start to build the photos app

## Tasks
- [x] Task 1 – create an app call photos
- [x] Task 2 – create serializers for this app
- [x] Task 3 – Make migration
- [x] Task 4 – Create urls for this app and include in the project urls
- [x] Task 5 – Create generic API listview for photos
- [x] Task 6 – Create generic API detailview for photos

## EPIC
1. #21
