### ISSUE TITLE
USER STORY: Create app for contacts

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kkimages-api#14]
As a **Developer** I can **add new apps to my project** so that **the project can be easily managed**

## Acceptance Criteria 1
**Given** that we have a database design
**When** we have a project to build apps on
**Then** we can start to build the contacts app

## Tasks
- [x] Task 1 – create an app call contacts
- [x] Task 2 – create serializers for this app
- [x] Task 3 – Make migration
- [x] Task 4 – Create urls for this app and include in the project urls
- [x] Task 5 – Create generic API listview for contacts
- [x] Task 6 – Create generic API detailview for contacts

## EPIC
1. #21
