### ISSUE TITLE
USER STORY: Create manual tests for apps

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kkimages-api#17]
As a **Developer** I can **create manual test cases for the apps** so that **I know the apps are functioning as intended**

## Acceptance Criteria 1
**Given** that we need to ensure the apps are working
**When** each app has been created
**Then** we need to test each app

## Tasks
- [x] Task 1 – Create test cases for the profiles
- [x] Task 2 – Create test cases for the albums
- [x] Task 3 – Create test cases for the photos
- [x] Task 4 – Create test cases for the comments
- [x] Task 5 – Create test cases for the likes
- [x] Task 6 – Create test cases for the followers
- [x] Task 7 – Create test cases for the contacts

## EPIC
1. #18
