### ISSUE TITLE
USER STORY: Deploy final project to Heroku

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kkimages-api#19]
As a **Developer** I can **deploy final version of the project to Heroku** so that **a live version with all the latest features of apps can be used**

## Acceptance Criteria 1
**Given** that the project will be shared to the public
**When** the project is ready to deploy
**Then** we can use Heroku to host our project

## Tasks
- [x] Task 1 – Setup JWT tokens in the project
- [x] Task 2 – Setup root route, pagination, JSON renderer and format for date and time
- [x] Task 3 – Create Heroku App with Heroku PostGres
- [x] Task 4 – Setup all environment variables like secret word and requirements.txt
- [x] Task 5 – Push the project to github
- [x] Task 6 – Connect project to heroku and deploy

## EPIC
1. #20
