### ISSUE TITLE
USER STORY: Deploy new project to Heroku early for development

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kkimages-api#4]
As a **Developer** I can **deploy a basic app to Heroku** so that **I can verify the app and connection to Heroku is working**

## Acceptance Criteria 1
**Given** that the project is going to run in Heroku
**When** the final development need to deploy to Heroku
**Then** an empty app can be deployed early to test all connections

## Tasks
- [x] Task 1 –  Run server to test app locally
- [x] Task 2 – Create  Procfile
- [x] Task 3 – Setup environment like secret word
- [x] Task 4 – Push project to github
- [x] Task 5 –  Connect project to Heroku and Deploy

## EPIC
1. #5
