### ISSUE TITLE
USER STORY: Update initial profiles model

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kkimages-api#6]
As a **Developer** I can **complete the profiles app as designed** so that **the we can store and retrieve users profile data**

## Acceptance Criteria 1
**Given** that the project has a database design
**When** the design has confirmed
**Then** it can implement to Django

## Tasks
- [x] Task 1 – Design and confirm profiles models
- [x] Task 2 – Set profiles models in Django
- [x] Task 3 – Use Django signals feature for creation of profiles
- [x] Task 4 – Create serializers.py for profiles app
- [x] Task 5 – make migration

## EPIC
1. #15
