### ISSUE TITLE
USER STORY: Install Django REST Frameworks

### ISSUE THREAD

**Issue by kkwong44** [kkwong44/kkimages-api#7]
As a **Developer** I can **user django rest framework** so that **I can create API views to our models**

## Acceptance Criteria 1
**Given** that the project will be used django rest framework
**When** we need to access the backend
**Then** this module need to be installed

## Tasks
- [x] Task 1 – Install django rest framework
- [x] Task 2 – update settings.py
- [x] Task 3 – Create profiles urls.py and include in project urls.py

## EPIC
1. #15
